from typing import List, Optional, Annotated, Literal, TypedDict
import operator
from pydantic import BaseModel, Field

# --- 1. The Plan Structure (What the Brain outputs) ---
class PlanStep(BaseModel):
    """A single tactical step in the research plan."""
    id: int = Field(description="Step number (1, 2, 3...)")
    title: str = Field(description="Short title of the step")
    query: str = Field(description="The precise search query or question to answer")
    tool: Literal["web_search", "document_search", "synthesis"] = Field(description="Which tool to use")
    reasoning: str = Field(description="Why this step is needed")

class ResearchPlan(BaseModel):
    """The Master Plan generated by the Planner Agent."""
    steps: List[PlanStep] = Field(description="List of steps to answer the user query")

# --- 2. The Agent State (Short-term Memory) ---
class AgentState(TypedDict):
    """
    The central state passed between LangGraph nodes.
    This is the 'Context Window' of our agent.
    """
    user_query: str
    
    # The Master Plan (List of dicts to be serializable)
    plan: List[dict] 
    
    # Current execution pointer
    current_step_index: int
    
    # Findings: We use operator.add to APPEND new findings, not overwrite
    findings: Annotated[List[str], operator.add]
    
    # Final Output
    final_answer: Optional[str]